### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/hactar-daemon#1]
New users need to be able to register their nodes and connect them to our web app to be able to track them.

Actions done through CLI:
1. Users enters email and password that was used to register on our app
2. Successful login (just pass everything for now until we reach integration point)
3. Detect miners and allow user to choose actor address (i.e. `t0101`)
4. Display token (read from `~/.lotus/token`) and URL of the node (this information is required for the user to add a node in our web app)
5. Save node (token, URL and actor address) to our backend

NOTE: Adding new nodes should be available always to the user as we can have multiple miners on one machine. We will use actor address to distinguish them.

**Comment by MakMuftic** [comment]
> 4. Display token (read from ~/.lotus/token) and **URL of the node** (this information is required for the user to add a node in our web app)

@morrigan I am not sure what is the source for this information (_URL of the node_)? Lotus JSON-RPC API or our backend?

Should we have an option to pass the location of a token file or is this location is fixed due to lotus?

**Comment by MakMuftic** [comment]
@morrigan Here is a snippet from the new README draft file, deamon app is started using **start** command. If a username or password is omitted as an option, the user will be prompted to enter them before anything happens. What do you think about this flow?

```
Available Commands:
  start       Starts hactar deamon app
  help        Help about any command
  version     Show the current version of Hactar deamon app

[start]:

    Starts hactar deamon app, connects with hactar service and starts monitoring process.

    Flags:
      -u, --username string         Username
      -p, --password string         Password
      -h, --help                    help for start command
```

**Comment by morrigan** [comment]
> > 1. Display token (read from ~/.lotus/token) and **URL of the node** (this information is required for the user to add a node in our web app)
> 
> @morrigan I am not sure what is the source for this information (_URL of the node_)? Lotus JSON-RPC API or our backend?

URL consists of the IP address and some unique ID, we send it to backend along with token so we know how to connect to it to request info. Shouldn't be hard to get that info I think. 

> Should we have an option to pass the location of a token file or is this location is fixed due to lotus?

Good question but I think it can't be changed inside lotus. Altough multiple tokens can be created, let's leave it for now until it becomes a feature request.

**Comment by morrigan** [comment]
@MakMuftic yep, seems good!
